language: php

sudo: false

php:
    - 5.3
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.3 WP_MULTISITE=0

matrix:
    allow_failures:
     - php: hhvm
     - php: 7.0

    include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=latest WP_MULTISITE=0

## Cache composer bits
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# Clones WordPress and configures our testing environment.
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION

script:
  - phpunit --coverage-clover clover.xml

after_script:
  # Push coverage off to Codecov
  - bash <(curl -s https://codecov.io/bash)